### ISSUE TITLE
Conflict with NServiceBus.Host

### ISSUE THREAD

**Issue by devindran** [SimonCropp/NServiceBus.ProtoBufNet#2]
I have set up 2 projects to test ProtoBufNet. One as a console application, and one as a class library intended to be consumed by a windows service.

All is well in the console app, but as I'm using NServiceBus.Host as a debug runner for the class library, I can't get the app to load if I have both references added. Note I have removed all code related to ProtoBufNet, only the reference is there.

Removing the reference allows my project to run correctly, adding it causes Visual Studio 2017 to enter a break mode with an exception shown in diagnostics as "Stopped at Exception".

Anyone else face this issue?

**Comment by SimonCropp** [comment]
FYI i have some proposed change in the licensing model for NuGet packages under the NServiceBusExtensions Org https://discuss.particular.net/t/proposed-change-in-the-licensing-model-for-nuget-packages-under-the-nservicebusextensions-org
